DROP DATABASE IF EXISTS PELICULAS;
CREATE DATABASE PELICULAS;
USE PELICULAS;


CREATE TABLE HONORIFICO(
	ID_HONORIFICO INT PRIMARY KEY AUTO_INCREMENT,
    HONORIFICO CHAR(5)    
);


CREATE TABLE USUARIO(
	ID_MEMBRESIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE CHAR(25),
    APELLIDOS CHAR(120),
    USUARIO CHAR(120),
    EDAD SMALLINT,
    ID_HONORIFICO INT,
    CONSTRAINT FK_USRGHR FOREIGN KEY (ID_HONORIFICO) REFERENCES HONORIFICO(ID_HONORIFICO)
	ON DELETE CASCADE ON UPDATE CASCADE
);


