

-- ######################################################
-- #########									#########
-- #########     PROCEDIMIENTOS USUARIOS        #########
-- #########									#########
-- ######################################################

-- ALTA USUARIO
DROP PROCEDURE IF EXISTS ALTA_USUARIO;
DELIMITER //
CREATE PROCEDURE ALTA_USUARIO( HONORIFICO_EXT CHAR(5), NOMBRE_EXT CHAR(25), APELLIDOS_EXT CHAR(120), EDAD_EXT SMALLINT,USUARIO_EXT CHAR(120))
BEGIN
	DECLARE USR INT;
	SET USR = (SELECT USUARIO.ID_MEMBRESIA FROM USUARIO WHERE USUARIO = USUARIO_EXT);
    IF USR >0 THEN
		SELECT "EL USUARIO YA EXISTE" AS MENSAJE;
    ELSE    
		CALL ALTA_HONORIFICO(HONORIFICO_EXT,@HONF);
		INSERT INTO USUARIO (NOMBRE,APELLIDOS,EDAD,USUARIO,ID_HONORIFICO) VALUES (NOMBRE_EXT,APELLIDOS_EXT,EDAD_EXT,USUARIO_EXT ,@HONF);
		SELECT "USUARIO REGISTRADO" AS MENSAJE;
	END IF;
END //

DELIMITER ;


-- BAJA USUARIO
DROP PROCEDURE IF EXISTS BAJA_USUARIO;
DELIMITER //
CREATE PROCEDURE BAJA_USUARIO(USUARIO_EXT CHAR(120))
BEGIN
	DECLARE USR INT;
	SET USR = (SELECT USUARIO.ID_MEMBRESIA FROM USUARIO WHERE USUARIO = USUARIO_EXT);
    IF USR >0 THEN
		DELETE FROM USUARIO WHERE ID_MEMBRESIA = USR;
        SELECT "USUARIO BORRADO" AS MENSAJE;
	ELSE
		SELECT "EL USUARIO NO EXISTE" AS MENSAJE;
    END IF;
END //	
DELIMITER ;


-- CAMBIO USUARIO
DROP PROCEDURE IF EXISTS CAMBIO_USUARIO;
DELIMITER //
CREATE PROCEDURE CAMBIO_USUARIO(HONORIFICO_EXT CHAR(5),HONORIFICO_NEW CHAR(5),
							    NOMBRE_EXT CHAR(25), APELLIDOS_EXT CHAR(120), EDAD_EXT SMALLINT,USUARIO_EXT CHAR(120),USUARIO_OLD CHAR(120))
BEGIN
	DECLARE USR INT;
    DECLARE USRN INT;
	SET USR = (SELECT USUARIO.ID_MEMBRESIA FROM USUARIO WHERE USUARIO = USUARIO_OLD);
    IF USR >0 THEN
		SET USRN = (SELECT USUARIO.ID_MEMBRESIA FROM USUARIO WHERE USUARIO = USUARIO_EXT);
		IF (USUARIO_EXT= USUARIO_OLD) THEN
			CALL CAMBIO_HONORIFICO(HONORIFICO_EXT,HONORIFICO_NEW,@HONF);
			UPDATE USUARIO SET
			NOMBRE = NOMBRE_EXT,
			APELLIDOS = APELLIDOS_EXT,
			EDAD = EDAD_EXT,
			ID_HONORIFICO = @HONF
				WHERE ID_MEMBRESIA = USR;
			SELECT "USUARIO ACTUALIZADO" AS MENSAJE;
            ELSE 
				IF USRN > 0 THEN
					SELECT "EL USUARIO YA EXISTE" AS MENSAJE;
				ELSE
					CALL CAMBIO_HONORIFICO(HONORIFICO_EXT,HONORIFICO_NEW,@HONF);
					UPDATE USUARIO SET
					NOMBRE = NOMBRE_EXT,
					APELLIDOS = APELLIDOS_EXT,
					EDAD = EDAD_EXT,
					USUARIO = USUARIO_EXT,
					ID_HONORIFICO = @HONF
					WHERE ID_MEMBRESIA = USR;
                    SELECT "USUARIO ACTUALIZADO" AS MENSAJE;
			END IF;
		END IF;
	ELSE
		SELECT "EL USUARIO NO EXISTE" AS MENSAJE;
    END IF;
END //                               

DELIMITER ;


-- CONSULTA USUARIO
DROP PROCEDURE IF EXISTS CONSULTA_USUARIO;
DELIMITER //
CREATE PROCEDURE CONSULTA_USUARIO(USUARIO_EXT CHAR(120))
BEGIN
	DECLARE USR INT;
	SET USR = (SELECT USUARIO.ID_MEMBRESIA FROM USUARIO WHERE USUARIO = USUARIO_EXT);
    IF USR >0 THEN
		SELECT HONORIFICO.HONORIFICO,
        USUARIO.NOMBRE,USUARIO.APELLIDOS,USUARIO.EDAD, USUARIO.USUARIO
        FROM USUARIO
        INNER JOIN HONORIFICO ON USUARIO.ID_HONORIFICO = HONORIFICO.ID_HONORIFICO
        WHERE USUARIO = USUARIO_EXT;
    ELSE
		SELECT "EL USUARIO NO EXISTE" AS MENSAJE;
    END IF;
    
END //


DELIMITER ;